"""
schemas/bill.py
===============
Typed data model for a Central Government legislative bill.

This schema is the canonical representation of a bill throughout the system.
All modules — ingestion, storage, NLP, mapping, labeling — must read and
write bills as ``Bill`` objects, never as raw dicts.

Migration Note
--------------
When Task 3 introduces pydantic, replace ``@dataclass`` with
``class Bill(pydantic.BaseModel)`` and add ``@validator`` decorators.
The field names and types will remain the same.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class BillStatus(str, Enum):
    """Life-cycle status of a bill in Parliament."""
    INTRODUCED = "introduced"       # Tabled in either house, debate not started
    PENDING = "pending"             # Under committee review or floor debate
    PASSED_LOK_SABHA = "passed_lok_sabha"
    PASSED_RAJYA_SABHA = "passed_rajya_sabha"
    PASSED_BOTH = "passed_both"     # Passed both houses; awaiting Presidential assent
    ASSENTED = "assented"           # Presidential assent received; now an Act
    LAPSED = "lapsed"               # Lapsed due to dissolution of Lok Sabha
    WITHDRAWN = "withdrawn"


class BillHouse(str, Enum):
    """House in which the bill was first introduced."""
    LOK_SABHA = "lok_sabha"
    RAJYA_SABHA = "rajya_sabha"


# ---------------------------------------------------------------------------
# Bill schema
# ---------------------------------------------------------------------------

@dataclass
class Bill:
    """
    Canonical representation of a Central Government legislative bill.

    Attributes
    ----------
    bill_id : str
        Unique slug identifier, e.g. ``"finance-bill-2024"``.
        Generated by ``utils.text_utils.slugify(title)``.
    title : str
        Official full title of the bill.
    bill_number : str
        Parliament bill number, e.g. ``"7/2024"`` or ``"Bill No. 125-C of 2023"``.
    year : int
        Year the bill was introduced.
    ministry : str
        Ministry or department sponsoring the bill.
    house : BillHouse
        House of first introduction (Lok Sabha or Rajya Sabha).
    status : BillStatus
        Current life-cycle status.
    introduction_date : date | None
        Date the bill was formally tabled.
    assent_date : date | None
        Date of Presidential assent (if applicable).
    gazette_date : date | None
        Date of notification in the Official Gazette.
    url : str
        Canonical URL to the official bill document or PRS summary.
    pdf_path : str | None
        Local filesystem path to the downloaded bill PDF.
    summary : str
        Short AI-generated or manually written summary (2–5 sentences).
    full_text : str
        Complete extracted text of the bill (from PDF or HTML).
    sectors : list[str]
        Economic sectors affected (populated by mapping module, Task 5).
    keywords : list[str]
        Key terms extracted from the bill text (populated by NLP, Task 4).
    source : str
        Data source identifier, e.g. ``"prs"``, ``"lok_sabha"``.
    ingested_at : date | None
        Date the record was first ingested into the system.
    """

    # Required fields
    bill_id: str
    title: str
    year: int
    ministry: str
    house: BillHouse
    status: BillStatus
    url: str

    # Optional fields (populated progressively by different pipeline stages)
    bill_number: str = ""
    introduction_date: Optional[date] = None
    assent_date: Optional[date] = None
    gazette_date: Optional[date] = None
    pdf_path: Optional[str] = None
    summary: str = ""
    full_text: str = ""
    sectors: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)
    source: str = "unknown"
    ingested_at: Optional[date] = None

    def to_dict(self) -> dict:
        """Serialise the Bill to a JSON-compatible dictionary."""
        return {
            "bill_id": self.bill_id,
            "title": self.title,
            "bill_number": self.bill_number,
            "year": self.year,
            "ministry": self.ministry,
            "house": self.house.value,
            "status": self.status.value,
            "introduction_date": self.introduction_date.isoformat() if self.introduction_date else None,
            "assent_date": self.assent_date.isoformat() if self.assent_date else None,
            "gazette_date": self.gazette_date.isoformat() if self.gazette_date else None,
            "url": self.url,
            "pdf_path": self.pdf_path,
            "summary": self.summary,
            "full_text": self.full_text,
            "sectors": self.sectors,
            "keywords": self.keywords,
            "source": self.source,
            "ingested_at": self.ingested_at.isoformat() if self.ingested_at else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Bill":
        """Deserialise a Bill from a dictionary (e.g. loaded from JSON)."""
        from utils.date_utils import parse_date  # noqa: PLC0415
        return cls(
            bill_id=data["bill_id"],
            title=data["title"],
            bill_number=data.get("bill_number", ""),
            year=int(data["year"]),
            ministry=data["ministry"],
            house=BillHouse(data["house"]),
            status=BillStatus(data["status"]),
            introduction_date=parse_date(data.get("introduction_date", "")),
            assent_date=parse_date(data.get("assent_date", "")),
            gazette_date=parse_date(data.get("gazette_date", "")),
            url=data.get("url", ""),
            pdf_path=data.get("pdf_path"),
            summary=data.get("summary", ""),
            full_text=data.get("full_text", ""),
            sectors=data.get("sectors", []),
            keywords=data.get("keywords", []),
            source=data.get("source", "unknown"),
            ingested_at=parse_date(data.get("ingested_at", "")),
        )

    def __repr__(self) -> str:
        return (
            f"<Bill bill_id={self.bill_id!r} year={self.year} "
            f"status={self.status.value!r} ministry={self.ministry!r}>"
        )
