"""
schemas/feature_validation_report.py
=====================================
Data model for validation failure reports generated by the
Feature Engineering Engine (Task 5.1).

When the engine encounters a FeatureRecord that fails one or more
validation checks (missing labels, duplicate pair, NaN numerics, …) it
emits a ``FeatureValidationReport`` instead of — or alongside — the
defective record.

Design
------
* Intentionally lightweight; downstream quality dashboards join back to
  bill/company metadata as needed.
* ``severity`` follows the same convention used in testing frameworks:
  ERROR   — record was rejected and excluded from the dataset
  WARNING — record was included with a degraded feature set
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class FeatureValidationReport:
    """
    Audit record for a FeatureRecord that failed a validation rule.

    Attributes
    ----------
    record_id : str
        Composite key ``{bill_id}|{company_isin}|{event_window}``.
    bill_id : str
        Bill slug of the failing record.
    company_isin : str
        Company ISIN of the failing record.
    event_window : str
        Event window that failed validation.
    severity : str
        ``"ERROR"`` (record excluded) or ``"WARNING"`` (record retained).
    failed_checks : list[str]
        One entry per violated rule, e.g. ``["missing_direction_label"]``.
    timestamp : str
        ISO-8601 UTC timestamp of the validation run.
    """

    record_id: str
    bill_id: str
    company_isin: str
    event_window: str
    severity: str                          # "ERROR" | "WARNING"
    failed_checks: list[str] = field(default_factory=list)
    timestamp: str = ""

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-compatible dictionary."""
        return {
            "record_id": self.record_id,
            "bill_id": self.bill_id,
            "company_isin": self.company_isin,
            "event_window": self.event_window,
            "severity": self.severity,
            "failed_checks": self.failed_checks,
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "FeatureValidationReport":
        """Deserialise a report from a dictionary."""
        return cls(
            record_id=data["record_id"],
            bill_id=data["bill_id"],
            company_isin=data["company_isin"],
            event_window=data["event_window"],
            severity=data.get("severity", "ERROR"),
            failed_checks=data.get("failed_checks", []),
            timestamp=data.get("timestamp", ""),
        )

    def __repr__(self) -> str:
        return (
            f"<FeatureValidationReport bill={self.bill_id!r} "
            f"isin={self.company_isin!r} "
            f"severity={self.severity!r} "
            f"checks={self.failed_checks!r}>"
        )
