"""
schemas/report.py
=================
Typed data models for the Stakeholder Reporting & Presentation Layer (Task 7.3).

Defines:
1. StakeholderType   — INVESTOR / BUSINESS / PUBLIC enum
2. ReportFormat      — JSON / MARKDOWN / CSV enum
3. StakeholderReport — Full per-(bill × company × stakeholder) report
4. BillLevelReport   — Aggregated bill-level summary across companies
5. CompanyLevelReport — Company → Bills aggregated view
6. ReportValidationReport — Pre-save validation audit
7. Deterministic ID generation helpers

Design Invariants
-----------------
- Reports are read-only views of DecisionSupportRecord outputs.
- No prediction logic, risk formulas, or ML models are present here.
- All probability and score fields are carried through verbatim from
  the upstream DecisionSupportRecord — never recomputed.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Helper: sanitize IDs for filesystem safety
# ---------------------------------------------------------------------------


def _sanitize(identifier: str) -> str:
    """Sanitize identifier string for deterministic OS-safe IDs."""
    if not identifier:
        return ""
    return (
        str(identifier)
        .replace("/", "_")
        .replace("\\", "_")
        .replace(":", "_")
        .replace(" ", "_")
        .replace("[", "")
        .replace("]", "")
        .replace("+", "p")
        .replace(",", "_")
    )


def make_report_id(
    bill_id: str,
    company_isin: str,
    event_window: str,
    stakeholder_type: str,
) -> str:
    """
    Generate a deterministic, unique report ID for a
    (bill, company, event_window, stakeholder_type) tuple.

    Formula: ``rpt_{bill_id}_{company_isin}_{event_window}_{stakeholder_type}``
    (all components sanitized for filesystem safety).
    """
    b = _sanitize(bill_id)
    i = _sanitize(company_isin)
    w = _sanitize(event_window)
    s = _sanitize(stakeholder_type).lower()
    return f"rpt_{b}_{i}_{w}_{s}"


def make_bill_report_id(bill_id: str) -> str:
    """Generate a deterministic ID for a bill-level aggregation report."""
    b = _sanitize(bill_id)
    return f"bill_rpt_{b}"


def make_company_report_id(company_isin: str) -> str:
    """Generate a deterministic ID for a company-level aggregation report."""
    i = _sanitize(company_isin)
    return f"co_rpt_{i}"


def make_validation_report_id(report_id: str) -> str:
    """Generate validation report ID from parent report ID."""
    return f"val_{report_id}"


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

REPORT_VERSION: str = "v1.0"

REPORT_DISCLAIMER: str = (
    "IMPORTANT DISCLAIMER: This report is an academic decision-support output generated by a "
    "quantitative research system. It does not constitute personalised investment advice, "
    "financial advice, or a recommendation to buy, sell, or hold any security. "
    "Predictions are probabilistic and may be incorrect. Past model performance does not "
    "guarantee future results. This system is intended for research and educational purposes only. "
    "Always consult a qualified financial advisor before making investment decisions."
)

REPORT_METHODOLOGY_NOTE: str = (
    "Methodology: Market impact predictions are generated using an ensemble of gradient-boosted "
    "tree models trained on historical Indian equity market data. Features include bill-level "
    "structured attributes, NLP embeddings (FinBERT / Legal-RoBERTa), event study abnormal "
    "returns, and SHAP-selected features. Anticipation scores quantify pre-event market activity "
    "using cumulative abnormal returns (CAR) across multiple pre-event windows. All scores and "
    "probabilities are model outputs — not guaranteed forecasts."
)


class StakeholderType(str, Enum):
    """Target stakeholder audience for a report."""

    INVESTOR = "INVESTOR"
    BUSINESS = "BUSINESS"
    PUBLIC = "PUBLIC"


class ReportFormat(str, Enum):
    """Serialisation format for report output."""

    JSON = "JSON"
    MARKDOWN = "MARKDOWN"
    CSV = "CSV"


# ---------------------------------------------------------------------------
# StakeholderReport
# ---------------------------------------------------------------------------


@dataclass
class StakeholderReport:
    """
    Strongly-typed, structured stakeholder report for a
    (bill × company × event_window × stakeholder_type) observation.

    This is a read-only presentation artefact — it does NOT modify
    predictions, risk scores, or any model outputs from upstream tasks.

    Fields
    ------
    report_id : str
        Deterministic unique identifier. Generated by ``make_report_id()``.
    bill_id : str
    company_isin : str
    event_window : str
    stakeholder_type : str
        One of INVESTOR / BUSINESS / PUBLIC.
    decision_version : str
        Version of the upstream DecisionSupportRecord used to build this report.
        Used for incremental regeneration checks.
    generated_timestamp : str
        ISO-8601 UTC timestamp of report generation.
    report_version : str
        Semantic version of the reporting engine (e.g. "v1.0").
    executive_summary : str
        2–3 sentence high-level summary tailored to the stakeholder type.
    bill_summary : str
        Bill name, type, ministry, house, introduction date.
    company_summary : str
        Company name, ISIN, sector, market cap category.
    impact_summary : str
        Direction probability, market-moving probability, impact score,
        impact category — presented in stakeholder-appropriate language.
    risk_summary : str
        Risk score, risk category, pricing-in risk — in audience language.
    anticipation_summary : str
        Anticipation classification and score interpretation.
    confidence_summary : str
        Model confidence tier and scalar score.
    key_factors : list[str]
        Top model factors (SHAP features where available) or narrative factors.
    methodology_note : str
        Fixed academic methodology statement.
    disclaimer : str
        Required legal/academic disclaimer text.
    """

    report_id: str
    bill_id: str
    company_isin: str
    event_window: str
    stakeholder_type: str
    decision_version: str
    generated_timestamp: str
    report_version: str
    executive_summary: str
    bill_summary: str
    company_summary: str
    impact_summary: str
    risk_summary: str
    anticipation_summary: str
    confidence_summary: str
    key_factors: list[str] = field(default_factory=list)
    methodology_note: str = ""
    disclaimer: str = ""

    def __post_init__(self) -> None:
        if not self.report_id:
            self.report_id = make_report_id(
                self.bill_id,
                self.company_isin,
                self.event_window,
                self.stakeholder_type,
            )
        if not self.generated_timestamp:
            self.generated_timestamp = (
                datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        return {
            "report_id": self.report_id,
            "bill_id": self.bill_id,
            "company_isin": self.company_isin,
            "event_window": self.event_window,
            "stakeholder_type": self.stakeholder_type,
            "decision_version": self.decision_version,
            "generated_timestamp": self.generated_timestamp,
            "report_version": self.report_version,
            "executive_summary": self.executive_summary,
            "bill_summary": self.bill_summary,
            "company_summary": self.company_summary,
            "impact_summary": self.impact_summary,
            "risk_summary": self.risk_summary,
            "anticipation_summary": self.anticipation_summary,
            "confidence_summary": self.confidence_summary,
            "key_factors": list(self.key_factors),
            "methodology_note": self.methodology_note,
            "disclaimer": self.disclaimer,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StakeholderReport":
        """Deserialise from a dictionary."""
        return cls(
            report_id=str(data.get("report_id", "")),
            bill_id=str(data.get("bill_id", "")),
            company_isin=str(data.get("company_isin", "")),
            event_window=str(data.get("event_window", "")),
            stakeholder_type=str(data.get("stakeholder_type", "")),
            decision_version=str(data.get("decision_version", "v1.0")),
            generated_timestamp=str(data.get("generated_timestamp", "")),
            report_version=str(data.get("report_version", "v1.0")),
            executive_summary=str(data.get("executive_summary", "")),
            bill_summary=str(data.get("bill_summary", "")),
            company_summary=str(data.get("company_summary", "")),
            impact_summary=str(data.get("impact_summary", "")),
            risk_summary=str(data.get("risk_summary", "")),
            anticipation_summary=str(data.get("anticipation_summary", "")),
            confidence_summary=str(data.get("confidence_summary", "")),
            key_factors=list(data.get("key_factors", [])),
            methodology_note=str(data.get("methodology_note", "")),
            disclaimer=str(data.get("disclaimer", "")),
        )


# ---------------------------------------------------------------------------
# BillLevelReport
# ---------------------------------------------------------------------------


@dataclass
class BillLevelReport:
    """
    Bill-level aggregation report across all companies affected by a single bill.

    Aggregation Formulas (documented)
    ----------------------------------
    - total_companies    : count of unique company ISINs in the input records
    - positive_count     : count where predicted_direction == "POSITIVE"
    - negative_count     : count where predicted_direction == "NEGATIVE"
    - neutral_count      : count where predicted_direction == "NEUTRAL"
    - market_moving_count: count where market_moving_probability >= 0.50
    - high_impact_count  : count where impact_category in {"HIGH", "VERY_HIGH"}
    - avg_impact_score   : arithmetic mean of impact_score values (NOT probabilities)
    - avg_risk_score     : arithmetic mean of risk_score values (NOT probabilities)
    - anticipation_distribution: frequency count of anticipation_class values
    - sectors_affected   : sorted unique list of sector values
    - risk_distribution  : frequency count of risk_category values
    """

    report_id: str
    bill_id: str
    bill_title: str
    bill_ministry: str
    bill_year: Optional[int]
    event_window: str
    generated_timestamp: str
    report_version: str
    total_companies: int
    positive_count: int
    negative_count: int
    neutral_count: int
    market_moving_count: int
    high_impact_count: int
    avg_impact_score: float
    avg_risk_score: float
    anticipation_distribution: dict[str, int]
    risk_distribution: dict[str, int]
    sectors_affected: list[str]
    company_summaries: list[dict[str, Any]] = field(default_factory=list)
    methodology_note: str = ""
    disclaimer: str = ""

    def __post_init__(self) -> None:
        if not self.report_id:
            self.report_id = make_bill_report_id(self.bill_id)
        if not self.generated_timestamp:
            self.generated_timestamp = (
                datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        return {
            "report_id": self.report_id,
            "bill_id": self.bill_id,
            "bill_title": self.bill_title,
            "bill_ministry": self.bill_ministry,
            "bill_year": self.bill_year,
            "event_window": self.event_window,
            "generated_timestamp": self.generated_timestamp,
            "report_version": self.report_version,
            "total_companies": self.total_companies,
            "positive_count": self.positive_count,
            "negative_count": self.negative_count,
            "neutral_count": self.neutral_count,
            "market_moving_count": self.market_moving_count,
            "high_impact_count": self.high_impact_count,
            "avg_impact_score": round(float(self.avg_impact_score), 4),
            "avg_risk_score": round(float(self.avg_risk_score), 4),
            "anticipation_distribution": dict(self.anticipation_distribution),
            "risk_distribution": dict(self.risk_distribution),
            "sectors_affected": list(self.sectors_affected),
            "company_summaries": list(self.company_summaries),
            "methodology_note": self.methodology_note,
            "disclaimer": self.disclaimer,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BillLevelReport":
        """Deserialise from a dictionary."""
        return cls(
            report_id=str(data.get("report_id", "")),
            bill_id=str(data.get("bill_id", "")),
            bill_title=str(data.get("bill_title", "")),
            bill_ministry=str(data.get("bill_ministry", "")),
            bill_year=data.get("bill_year"),
            event_window=str(data.get("event_window", "")),
            generated_timestamp=str(data.get("generated_timestamp", "")),
            report_version=str(data.get("report_version", "v1.0")),
            total_companies=int(data.get("total_companies", 0)),
            positive_count=int(data.get("positive_count", 0)),
            negative_count=int(data.get("negative_count", 0)),
            neutral_count=int(data.get("neutral_count", 0)),
            market_moving_count=int(data.get("market_moving_count", 0)),
            high_impact_count=int(data.get("high_impact_count", 0)),
            avg_impact_score=float(data.get("avg_impact_score", 0.0)),
            avg_risk_score=float(data.get("avg_risk_score", 0.0)),
            anticipation_distribution=dict(
                data.get("anticipation_distribution", {})
            ),
            risk_distribution=dict(data.get("risk_distribution", {})),
            sectors_affected=list(data.get("sectors_affected", [])),
            company_summaries=list(data.get("company_summaries", [])),
            methodology_note=str(data.get("methodology_note", "")),
            disclaimer=str(data.get("disclaimer", "")),
        )


# ---------------------------------------------------------------------------
# CompanyLevelReport
# ---------------------------------------------------------------------------


@dataclass
class CompanyLevelReport:
    """
    Company-level aggregation report showing all bills that may affect a company.

    Supports both:
    - Bill → Company queries (single company filtered from BillLevelReport)
    - Company → Bills queries (all bills affecting this company ISIN)
    """

    report_id: str
    company_isin: str
    company_name: str
    company_sector: str
    generated_timestamp: str
    report_version: str
    total_bills: int
    positive_bill_count: int
    negative_bill_count: int
    neutral_bill_count: int
    avg_impact_score: float
    avg_risk_score: float
    bill_summaries: list[dict[str, Any]] = field(default_factory=list)
    high_impact_bills: list[str] = field(default_factory=list)
    methodology_note: str = ""
    disclaimer: str = ""

    def __post_init__(self) -> None:
        if not self.report_id:
            self.report_id = make_company_report_id(self.company_isin)
        if not self.generated_timestamp:
            self.generated_timestamp = (
                datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        return {
            "report_id": self.report_id,
            "company_isin": self.company_isin,
            "company_name": self.company_name,
            "company_sector": self.company_sector,
            "generated_timestamp": self.generated_timestamp,
            "report_version": self.report_version,
            "total_bills": self.total_bills,
            "positive_bill_count": self.positive_bill_count,
            "negative_bill_count": self.negative_bill_count,
            "neutral_bill_count": self.neutral_bill_count,
            "avg_impact_score": round(float(self.avg_impact_score), 4),
            "avg_risk_score": round(float(self.avg_risk_score), 4),
            "bill_summaries": list(self.bill_summaries),
            "high_impact_bills": list(self.high_impact_bills),
            "methodology_note": self.methodology_note,
            "disclaimer": self.disclaimer,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CompanyLevelReport":
        """Deserialise from a dictionary."""
        return cls(
            report_id=str(data.get("report_id", "")),
            company_isin=str(data.get("company_isin", "")),
            company_name=str(data.get("company_name", "")),
            company_sector=str(data.get("company_sector", "")),
            generated_timestamp=str(data.get("generated_timestamp", "")),
            report_version=str(data.get("report_version", "v1.0")),
            total_bills=int(data.get("total_bills", 0)),
            positive_bill_count=int(data.get("positive_bill_count", 0)),
            negative_bill_count=int(data.get("negative_bill_count", 0)),
            neutral_bill_count=int(data.get("neutral_bill_count", 0)),
            avg_impact_score=float(data.get("avg_impact_score", 0.0)),
            avg_risk_score=float(data.get("avg_risk_score", 0.0)),
            bill_summaries=list(data.get("bill_summaries", [])),
            high_impact_bills=list(data.get("high_impact_bills", [])),
            methodology_note=str(data.get("methodology_note", "")),
            disclaimer=str(data.get("disclaimer", "")),
        )


# ---------------------------------------------------------------------------
# ReportValidationReport
# ---------------------------------------------------------------------------


@dataclass
class ReportValidationReport:
    """
    Validation audit report generated during report pre-save checks.
    """

    validation_id: str
    report_id: str
    bill_id: str
    company_isin: str
    stakeholder_type: str
    is_valid: bool = True
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    checks_performed: dict[str, bool] = field(default_factory=dict)
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc)
        .isoformat()
        .replace("+00:00", "Z")
    )

    def __post_init__(self) -> None:
        if self.errors:
            self.is_valid = False
        if not self.validation_id:
            self.validation_id = make_validation_report_id(self.report_id)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        return {
            "validation_id": self.validation_id,
            "report_id": self.report_id,
            "bill_id": self.bill_id,
            "company_isin": self.company_isin,
            "stakeholder_type": self.stakeholder_type,
            "is_valid": bool(self.is_valid),
            "errors": list(self.errors),
            "warnings": list(self.warnings),
            "checks_performed": dict(self.checks_performed),
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ReportValidationReport":
        """Deserialise from a dictionary."""
        return cls(
            validation_id=str(data.get("validation_id", "")),
            report_id=str(data.get("report_id", "")),
            bill_id=str(data.get("bill_id", "")),
            company_isin=str(data.get("company_isin", "")),
            stakeholder_type=str(data.get("stakeholder_type", "")),
            is_valid=bool(data.get("is_valid", True)),
            errors=list(data.get("errors", [])),
            warnings=list(data.get("warnings", [])),
            checks_performed=dict(data.get("checks_performed", {})),
            timestamp=str(data.get("timestamp", "")),
        )
